### ISSUE TITLE
Error running webhook listener

### ISSUE THREAD

**Issue by thestriver** [alchemyplatform/webhook-examples#3]
Hi,
So I would say my node.js is a bit rusty but I was hoping to get results by following the readme. Just like a reader of the docs would do.
So I followed all the instructions and then run `PORT=8080 HOST=localhost SIGNING_KEY=whsec_7********* yarn start` while replace the SIGNING_KEY while updating the webhook path in line 30 to `app.post('https://immense-ravine-####.herokuapp.com/alchemyhook', (req, res) => {`

I've copied the error I got below.

```
TypeError: Cannot read properties of undefined (reading 'rawBody')
    at isValidSignatureForAlchemyRequest (/Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/src/webhooksUtil.ts:19:21)
    at /Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/src/webhooksUtil.ts:53:10
    at Layer.handle [as handle_request] (/Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/node_modules/express/lib/router/index.js:328:13)
    at /Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mahmud/Documents/Code/Alchemy/webhook-examples/node-express/node_modules/express/lib/router/index.js:328:13)
````

**Comment by 777genius** [comment]
You need to test using "Send Test Notification"
<img width="272" alt="image" src="https://github.com/alchemyplatform/webhook-examples/assets/13103045/8b5a1d5f-448a-411c-a38c-402a7b4f11e4">
